version: "3.8"

services:
  thrilldigger:
    build: .
    container_name: thrilldigger-server
    ports:
      - "443:443"
    volumes:
      - ./db:/app/db
      - /etc/letsencrypt:/certs:ro
    working_dir: /app
    command: bash -c "source /emsdk/emsdk_env.sh && python server.py"
    environment:
      - CERT_PATH=/certs/live/digthriller.win/fullchain.pem
      - KEY_PATH=/certs/live/digthriller.win/privkey.pem
